# Site settings
author: Christina "Chrissy" Benbeneck 
title: Chronicles of a Nurse turned Developer 
header-img: img/home-bg.png
email: cbenbeneck@mail.usf.edu
copyright_name: Christina "Chrissy" Benbeneck 
description: > # this means to ignore newlines until "baseurl:"
  A log of my software engineering experience
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: chrisben88
github_username:  cbenbeneck

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
